# Prueba1

Importar numpy

In [1]:
import numpy as np

Ejemplos

In [9]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0]

1

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matriz[0][2]

3

In [18]:
matriz[0,2]

3

In [19]:
arr[0:3]

array([1, 2, 3])

In [20]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[::2]

array([1, 3, 5, 7, 9])

In [22]:
arr [-1]

9

In [23]:
matriz[1: , 0:2]

array([[4, 5],
       [7, 8]])