# Tipos de Datos

Importar

In [8]:
import numpy as np


Ejemplos

In [5]:
arr = np.array([1,2,3,4])
arr.dtype #muestra el tipo de datos de los elementos

dtype('int32')

In [4]:
arr = np.array([1,2,3,4], dtype= 'float64')
arr.dtype  #cambio de tipo a flotante

dtype('float64')

In [6]:
arr = np.array([1,2,3,4])
arr = arr.astype(np.float64) 
arr.dtype
#para cambiar de tipo de datos a un
#array ya creado

dtype('float64')

In [7]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int64)
arr

array([0, 1, 2, 3, 4], dtype=int64)

## Dimensiones clase 4/24


In [9]:
scalar = np.array(41)
print(scalar)
scalar.ndim

41


0

In [13]:
matriz = np.array([[1,2,3,4],[5,6,7,8]])
print(matriz)
matriz.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [14]:
tensor = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(tensor)
tensor.ndim

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


3

Agregar o eliminar dimensiones


In [16]:
vector = np.array([1,2,3,4], ndmin =10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [17]:
expand =np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [18]:
print(vector,vector.ndim)
vector2 = np.squeeze(vector)
print(vector2,vector2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1


# Creando arrays


In [20]:
list(range(0,10)) # para crear una lista de inicio 0 hasta 10 excluyente

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
np.arange(0,10) # devuelve el codigo anterior en formato array de numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [31]:
np.zeros(3)


array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.linspace(0,11,4)
# linspace crea un inicio y un fin y crea una lista espaciado
# de manera ordenada con x elementos (4)

array([ 0.        ,  3.66666667,  7.33333333, 11.        ])

In [39]:
np.eye(5) 
# crea una matriz diagonal n*n (5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.random.rand()
#crea un numero aleatorio entre 0 y 1

0.025577213516117192

In [45]:
np.random.rand(4,2)
#crea un array de x * y * z * ... elementos de numeros aleatorios

array([[0.48468511, 0.75925583],
       [0.99983319, 0.73543117],
       [0.98064866, 0.22016684],
       [0.73902046, 0.66816875]])

In [59]:
eje = np.random.randint(1,100)
print(eje) # Imprime un numero aleatorio entre el rango dado
eje =np.random.randint(1,100 , (3,8))
print(eje) #Imprime un numero aleatorioe entre el rango dado en un array

65
[[41 60 33 51 97 40 22 97]
 [97 46 53 41 93 13 41 47]
 [56 91 20 61 85 61 85 84]]


# Shape y ReShape

In [61]:
arr = np.random.randint(1,10,(3,2))
arr

array([[3, 8],
       [7, 3],
       [5, 1]])

In [63]:
arr.shape #muestra las dimensiones del array

(3, 2)

In [65]:
arr.reshape(1,6) # reordena los elementos del array para ajustarlo
# a una dimension especificada

array([[3, 8, 7, 3, 5, 1]])

In [66]:
arr.reshape(2,3)

array([[3, 8, 7],
       [3, 5, 1]])

In [67]:
np.reshape(arr, (1,6))

array([[3, 8, 7, 3, 5, 1]])

In [72]:
print(arr)
print("\n",np.reshape(arr,(2,3),"C")) #Segun lenguaje C
print("\n",np.reshape(arr,(2,3),"F")) #Segun lenguaje fortrant
print("\n",np.reshape(arr,(2,3),"A")) #Segun optimizado mi sistema

[[3 8]
 [7 3]
 [5 1]]

 [[3 8 7]
 [3 5 1]]

 [[3 5 3]
 [7 8 1]]

 [[3 8 7]
 [3 5 1]]


# Funciones principales de Numpy

In [74]:
array = np.random.randint(1,20,10)
matriz = array.reshape(2,5)
matriz

array([[16, 17,  7,  9,  4],
       [16, 10,  5,  1, 16]])

In [79]:
print(array.max()) # Muestra el maximo
print(matriz.max(0)) # 0 = eje de columans
print(matriz.max(1)) # 1 = eje de filas
print(array.argmax()) # dice el indice donde se encuentra el maximo

17
[16 17  7  9 16]
[17 16]
1


In [80]:
print(array.min()) #Muestra el minimo
print(array.argmin()) #FUnciona igual que el max

1
8


In [85]:
print(array)
print(array.ptp()) #Muestra la distancia entre el maximo y el minimo
print(matriz)
matriz.ptp(1)

[16 17  7  9  4 16 10  5  1 16]
16
[[16 17  7  9  4]
 [16 10  5  1 16]]


array([13, 15])

In [98]:
print(array)
print(np.percentile(array,50) )#percentiles
array.sort() #ordena de menor a mayor

print(np.median(array)) #Entrega la mediana de un array
print(np.median(matriz,1))

print(np.std(array)) # desviacion estandar de un array
print(np.var(arr)) # varianza
print(np.mean(arr)) # media

[ 1  4  5  7  9 10 16 16 16 17]
9.5
9.5
[ 5. 16.]
5.5578772926361015
5.916666666666667
4.5


In [101]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = np.expand_dims(b,axis=0)

np.concatenate([a,b], axis =0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
np.concatenate([a,b.T], axis =1) #.T traspuesta de un array

array([[1, 2, 5],
       [3, 4, 6]])

# Copy

In [112]:
array


array([ 0,  0,  0,  0,  0,  0, 16, 16, 16, 17])

In [113]:
trozo_array = array[0:6]
trozo_array[:] = 0
trozo_array

array([0, 0, 0, 0, 0, 0])

In [114]:
array # Los cambios en trozo_array acaban de modificar el array original

array([ 0,  0,  0,  0,  0,  0, 16, 16, 16, 17])

In [120]:
#Para solucionar este problema usar el comando copy
array_copy = array.copy()
array_copy[:] = 100
print(array)
array_copy

[ 0  0  0  0  0  0 16 16 16 17]


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# Condiciones

In [122]:
array2 = np.linspace(1,10,10, dtype="int8")
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [124]:
indices_cond = array2 >5
indices_cond # arroja un array booleano

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [127]:
print(array2[indices_cond]) #Devuelve el array cuyos elementos si cumplan 
print(array2[array2>5])

print(array2[(array2>5) & (array2<9)])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[6 7 8]


# Funciones

In [128]:
#operaciones con numpy
arr3 = np.arange(0,10)
arr4 = arr3.copy()

In [132]:
print(arr3)
print(arr3 * 2)  # multiplicar
print(arr3 +2)    # Suma
print(1/arr3[1:]) # division

print(arr3+arr4) # suma de dos arrays elemento por elemento de su indice

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[ 0  2  4  6  8 10 12 14 16 18]


In [135]:
matriz = arr3.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
print(matriz + matriz2) #Suma
print(matriz - matriz2) #Resta
print(np.matmul(matriz, matriz2.T)) #Producto punto
print(matriz @ matriz2.T) #Otra manera de producto punto


[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
